### ISSUE TITLE
A little issue with Copy Paste :)

### ISSUE THREAD

**Issue by bmagic** [veo-labs/openveo-api#1]
In file  openveo-api/lib/database/mongodb/MongoDatabase.js

line 48 this.conf.username is used instead of  this.conf.password. 
var connectionUrl = 'mongodb://' + this.conf.username + ':' + this.conf.username + '@' + this.conf.host + ':' + this.conf.port;

Sorry, no time for pull requests ;)

**Comment by pchampclos-veolabs** [comment]
A fix is included in 1.0.0.
Thanks for reporting this issue.
